import { NextResponse } from 'next/server';

// Static quiz data served from API
const QUIZ_QUESTIONS = [
  { id:'ml1',category:'ml',difficulty:'easy',question:'What is overfitting in machine learning?',options:['When a model trains too slowly','When a model performs well on training data but poorly on unseen data','When a model has too few parameters','When a model ignores the training data entirely'],answer:1,explanation:'Overfitting occurs when a model memorizes training data including its noise, causing it to perform poorly on new, unseen examples.',hint:'Think about memorizing vs understanding.' },
  { id:'ml2',category:'ml',difficulty:'easy',question:'What is the purpose of cross-validation?',options:['To speed up model training','To evaluate model performance on unseen data reliably','To clean the training dataset','To increase model complexity'],answer:1,explanation:'Cross-validation splits data into multiple folds to get a robust estimate of how a model will perform on unseen data.',hint:'It is about reliable evaluation.' },
  { id:'ml3',category:'ml',difficulty:'medium',question:'What does gradient descent minimize?',options:['Model complexity','Training time','The loss function','Dataset size'],answer:2,explanation:'Gradient descent iteratively adjusts model parameters in the direction opposite to the gradient of the loss function.',hint:'It is related to errors and optimization.' },
  { id:'ml4',category:'ml',difficulty:'medium',question:'What is regularization used for?',options:['To increase training speed','To add more data to training','To prevent overfitting by penalizing model complexity','To normalize input features'],answer:2,explanation:'Regularization (L1/L2) adds a penalty term to the loss function based on model weight magnitudes, discouraging overfitting.',hint:'It constrains the model freedom.' },
  { id:'ml5',category:'ml',difficulty:'easy',question:'What is the difference between classification and regression?',options:['Classification is faster; regression is more accurate','Classification predicts categories; regression predicts continuous values','Classification uses more data; regression uses less','Classification is supervised; regression is unsupervised'],answer:1,explanation:'Classification predicts discrete categories (spam/not spam), while regression predicts continuous numerical values (house price).',hint:'One deals with labels, the other with numbers.' },
  { id:'ml6',category:'ml',difficulty:'medium',question:'What does a confusion matrix show?',options:['How confused the model is during training','The correlation between features','A table of true/false positives and negatives for classification','The gradient of the loss function'],answer:2,explanation:'A confusion matrix is a table showing the counts of TP, TN, FP, FN.',hint:'It breaks down prediction correctness in detail.' },
  { id:'ml7',category:'ml',difficulty:'medium',question:'What is ensemble learning?',options:['Training one very large model','Using multiple models together for better performance','Ensuring data quality before training','Training models in parallel to save time'],answer:1,explanation:'Ensemble methods combine predictions from multiple models, reducing variance and bias.',hint:'Many are better than one.' },
  { id:'ml8',category:'ml',difficulty:'easy',question:'What does K-means clustering do?',options:['Randomly assigns labels without iteration','Groups data into K clusters by iteratively assigning points to nearest centroids','Uses supervised labels to cluster data','Finds clusters using a decision tree'],answer:1,explanation:'K-means iteratively assigns each point to its nearest centroid, then updates centroids as the mean of assigned points.',hint:'Think about centers and distance.' },
  { id:'ml9',category:'ml',difficulty:'hard',question:'What is the bias-variance tradeoff?',options:['Trading speed for accuracy','The balance between model simplicity (high bias) and flexibility (high variance)','The tradeoff between training and test set sizes','The choice between classification and regression'],answer:1,explanation:'High bias = underfitting; High variance = overfitting. Optimal model balances both.',hint:'Underfitting vs overfitting.' },
  { id:'ml10',category:'ml',difficulty:'medium',question:'What does PCA primarily do?',options:['Classifies data into clusters','Reduces dimensionality while preserving maximum variance','Increases model accuracy','Cleans outliers from data'],answer:1,explanation:'PCA finds orthogonal components that explain the most variance in the data.',hint:'It compresses data representation.' },
  { id:'dl1',category:'dl',difficulty:'easy',question:'What is backpropagation?',options:['Training data that flows backwards','An algorithm to calculate gradients in neural networks by propagating error backwards','A method to reverse-engineer a neural network','Running a neural network from output to input'],answer:1,explanation:'Backpropagation uses the chain rule of calculus to efficiently compute gradients of the loss.',hint:'It computes gradients layer by layer.' },
  { id:'dl2',category:'dl',difficulty:'easy',question:'What are CNNs primarily used for?',options:['Processing text sequences','Financial time series forecasting','Image and visual data processing','Reinforcement learning environments'],answer:2,explanation:'CNNs use convolutional layers to automatically learn spatial hierarchies of features in images.',hint:'They excel with grid-like data.' },
  { id:'dl3',category:'dl',difficulty:'medium',question:'What is dropout in deep learning?',options:['When training stops early due to overfitting','Removing poorly performing neurons permanently','A regularization technique that randomly disables neurons during training','The learning rate dropping to zero'],answer:2,explanation:'Dropout randomly sets a fraction of neuron activations to zero during training, preventing co-adaptation.',hint:'It introduces randomness to prevent memorization.' },
  { id:'dl4',category:'dl',difficulty:'hard',question:'What is the vanishing gradient problem?',options:['When gradients become too large','When gradients become extremely small, preventing weight updates in early layers','When the loss function disappears','When a neural network forgets data'],answer:1,explanation:'In deep networks, gradients multiplied through many layers can become exponentially small.',hint:'Think about multiplying small numbers many times.' },
  { id:'dl5',category:'dl',difficulty:'medium',question:'What does transfer learning allow you to do?',options:['Move a model to different hardware','Transfer data between datasets','Use a pre-trained model as a starting point for a new related task','Transfer knowledge between two students'],answer:2,explanation:'Transfer learning leverages features learned from large datasets by fine-tuning on your target dataset.',hint:'Standing on the shoulders of giants.' },
  { id:'dl6',category:'dl',difficulty:'medium',question:'What does GAN stand for?',options:['Gradient Accumulation Network','Generative Adversarial Network','Global Attention Network','Graph Alignment Network'],answer:1,explanation:'GANs have a Generator creating fake data and a Discriminator trying to detect fakes.',hint:'Two networks competing against each other.' },
  { id:'dl7',category:'dl',difficulty:'medium',question:'What problem were LSTMs designed to solve?',options:['Image classification','Long-term dependencies in sequential data that vanilla RNNs struggle with','Reducing model size','Improving batch normalization'],answer:1,explanation:'LSTMs use gating mechanisms with a cell state to selectively remember and forget information over long sequences.',hint:'It is about memory over long sequences.' },
  { id:'dl8',category:'dl',difficulty:'easy',question:'What is batch normalization?',options:['Dividing data into equal-sized batches','Normalizing layer inputs across a batch to stabilize and speed up training','Removing outlier samples from batches','Normalizing gradient magnitudes'],answer:1,explanation:'Batch norm normalizes activations to have zero mean and unit variance.',hint:'It normalizes within each layer.' },
  { id:'dl9',category:'dl',difficulty:'medium',question:'What is an autoencoder used for?',options:['Automatically coding programs','Supervised image classification','Learning compressed latent representations of data unsupervised','Auto-tuning hyperparameters'],answer:2,explanation:'Autoencoders compress input to a latent space then reconstruct it.',hint:'Compress and reconstruct.' },
  { id:'dl10',category:'dl',difficulty:'hard',question:'What is the attention mechanism in transformers?',options:['A technique to focus model training on hard examples','A method for the model to weigh the relevance of different input positions when producing output','A regularization technique','An optimization algorithm'],answer:1,explanation:'Attention computes weighted sums of value vectors based on query-key similarity.',hint:'How much should each word pay attention to others?' },
  { id:'nlp1',category:'nlp',difficulty:'easy',question:'What is tokenization in NLP?',options:['Converting images to text','Breaking text into smaller units (tokens) for model processing','Encrypting text for security','Removing stop words from text'],answer:1,explanation:'Tokenization splits text into units that the model can process numerically.',hint:'It is the first preprocessing step for text.' },
  { id:'nlp2',category:'nlp',difficulty:'easy',question:'What does BERT stand for?',options:['Bidirectional Encoder Representations from Transformers','Binary Encoding and Representation Technique','Batch Embedding Recurrent Training','Bidirectional Evaluation Reasoning Transformer'],answer:0,explanation:'BERT by Google is pre-trained to understand context from both left and right simultaneously.',hint:'B=Bidirectional, E=Encoder, R=Representations...' },
  { id:'nlp3',category:'nlp',difficulty:'medium',question:'What is RAG in AI?',options:['Recursive Autoregressive Generation','Retrieval Augmented Generation – enhancing LLMs with external knowledge lookup','Regularized Attention Gradient','Random Augmentation of Graphs'],answer:1,explanation:'RAG retrieves relevant documents and provides them as context to the LLM.',hint:'It gives LLMs access to external knowledge.' },
  { id:'nlp4',category:'nlp',difficulty:'easy',question:'What is hallucination in LLMs?',options:['When the model generates creative fiction intentionally','When the model generates confident but factually incorrect information','When the model refuses to answer questions','When the model sees images in text'],answer:1,explanation:'LLM hallucination occurs when the model generates plausible-sounding but false information.',hint:'Convincingly wrong.' },
  { id:'nlp5',category:'nlp',difficulty:'medium',question:'What is the context window in LLMs?',options:['The time window for model training','The popup showing model context','The maximum amount of tokens an LLM can process at once','The window of attention for each token'],answer:2,explanation:'The context window defines how much text the model can see at once.',hint:'How much can the model hold in memory at once?' },
  { id:'nlp6',category:'nlp',difficulty:'medium',question:'What is fine-tuning an LLM?',options:['Adjusting inference speed','Training a pre-trained model further on specific domain data to specialize it','Fine-grained hyperparameter search','Reducing model size through pruning'],answer:1,explanation:'Fine-tuning updates a pre-trained model weights on task-specific data.',hint:'Teaching an existing expert your specific domain.' },
  { id:'nlp7',category:'nlp',difficulty:'medium',question:'What are word embeddings used for?',options:['Embedding hidden messages in text','Converting words into dense numerical vectors that capture semantic meaning','Compressing text files','Encrypting word data'],answer:1,explanation:'Word embeddings map words to vectors where semantic similarity equals geometric proximity.',hint:'Words become numbers in a meaningful space.' },
  { id:'nlp8',category:'nlp',difficulty:'hard',question:'What is few-shot learning in the context of LLMs?',options:['Training a model with only a few GPU shots','Using a model that was trained on few examples','Including a few input-output examples in the prompt to guide model behavior','Reducing model size to require fewer resources'],answer:2,explanation:'Few-shot prompting includes 2-10 examples in the prompt, allowing the LLM to infer the task pattern.',hint:'Examples in the prompt, not in the training.' },
  { id:'nlp9',category:'nlp',difficulty:'medium',question:'What does GPT stand for?',options:['General Purpose Transformer','Generative Pre-trained Transformer','Gradient Propagation Technique','Guided Prediction Training'],answer:1,explanation:'GPT (Generative Pre-trained Transformer) is a decoder-only transformer pre-trained on vast text.',hint:'G=Generative, P=Pre-trained...' },
  { id:'nlp10',category:'nlp',difficulty:'hard',question:'How is semantic search different from keyword search?',options:['Semantic search is faster','Semantic search uses vector embeddings to find conceptually similar results, not just keyword matches','Semantic search only works with structured data','Semantic search requires less computing power'],answer:1,explanation:'Semantic search embeds queries and documents in vector space and finds nearest neighbors by meaning.',hint:'Meaning vs exact words.' },
  { id:'pe1',category:'pe',difficulty:'easy',question:'What is chain-of-thought (CoT) prompting?',options:['Chaining multiple API calls together','Asking the model to show its reasoning step-by-step before answering','A sequence of prompts for different tasks','Linking prompts to external databases'],answer:1,explanation:'CoT prompting dramatically improves reasoning by getting the model to articulate intermediate steps.',hint:'"Think step by step" is the classic trigger.' },
  { id:'pe2',category:'pe',difficulty:'easy',question:'What does "temperature" control in LLM generation?',options:['How fast the model generates text','The model GPU temperature','The randomness and creativity of outputs (higher = more random)','The length of generated responses'],answer:2,explanation:'Temperature scales the logit distribution before sampling. Low temp for factual tasks, higher for creative.',hint:'Hot = creative, cold = precise.' },
  { id:'pe3',category:'pe',difficulty:'easy',question:'What is zero-shot prompting?',options:['Shooting for zero errors in a prompt','Asking the model to perform a task with no examples in the prompt','A prompt with zero instructions','Using a model with zero training'],answer:1,explanation:'Zero-shot prompting relies entirely on the model pre-trained knowledge without examples.',hint:'Zero examples, just instructions.' },
  { id:'pe4',category:'pe',difficulty:'medium',question:'What is prompt injection?',options:['Injecting code into a model weights','Malicious input designed to override or hijack the AI instructions','Inserting variables into prompt templates','A technique to make prompts shorter'],answer:1,explanation:'Prompt injection attacks try to override the system prompt by embedding conflicting instructions.',hint:'A security vulnerability in AI systems.' },
  { id:'pe5',category:'pe',difficulty:'medium',question:'What is role prompting?',options:['Assigning database roles to AI','Prompting the model to take on a specific persona or expert role','Listing the model available roles','Rotating between different prompts'],answer:1,explanation:'Role prompting activates relevant knowledge and adjusts tone for specialized tasks.',hint:'"You are a..." is the classic format.' },
  { id:'pe6',category:'pe',difficulty:'medium',question:'What is the purpose of delimiters in prompts?',options:['To make prompts look more professional','To clearly separate different sections of input, reducing ambiguity','To encrypt sensitive parts of prompts','To trigger specific model behaviors'],answer:1,explanation:'Delimiters clearly demarcate instructions from content, helping the model understand prompt structure.',hint:'Clarity and structure.' },
  { id:'pe7',category:'pe',difficulty:'hard',question:'What is ReAct prompting?',options:['A React.js integration for LLMs','Reactive prompting that adapts based on user emotion','A framework combining Reasoning + Acting, letting models use tools interleaved with thought','A prompt refinement technique using feedback'],answer:2,explanation:'ReAct prompts the model to alternate between Thought (reasoning) and Action (tool use) steps.',hint:'Think, act, observe, repeat.' },
  { id:'pe8',category:'pe',difficulty:'easy',question:'What is a system prompt?',options:['A prompt sent by the operating system','Instructions that set the AI role, behavior, and constraints for the entire session','A prompt that generates other prompts','The first message in a conversation'],answer:1,explanation:'System prompts set the AI persona, rules, and capabilities and persist throughout the conversation.',hint:'It sets the stage for all interactions.' },
  { id:'pe9',category:'pe',difficulty:'medium',question:'Why specify output format in prompts?',options:['To make the model work faster','To reduce hallucination rates','To get structured, predictable responses for downstream processing','To limit response length'],answer:2,explanation:'Specifying output format makes responses machine-parseable and consistent for programmatic use.',hint:'Structure the output for your use case.' },
  { id:'pe10',category:'pe',difficulty:'hard',question:'What is Constitutional AI (CAI)?',options:['AI systems built according to national constitutions','A training approach using principles for the AI to self-critique and revise its outputs','A legal framework for AI regulation','AI that can write legal documents'],answer:1,explanation:'Constitutional AI trains AI using natural language principles to self-critique and revise responses.',hint:'Self-improvement guided by principles.' },
  { id:'e1',category:'ethics',difficulty:'easy',question:'What is AI bias?',options:['When an AI model is biased toward fast answers','When AI systems reflect, amplify, or perpetuate human prejudices from training data','When an AI is programmed to prefer one option','A statistical term for model variance'],answer:1,explanation:'AI bias occurs when training data or design choices encode societal prejudices, causing unfair outcomes.',hint:'Data reflects society existing inequalities.' },
  { id:'e2',category:'ethics',difficulty:'medium',question:'What is explainable AI (XAI)?',options:['AI that can explain jokes','AI systems whose decision-making processes can be understood and interpreted by humans','An AI that explains itself to other AIs','Simplified AI with fewer parameters'],answer:1,explanation:'XAI makes AI decisions interpretable — crucial for high-stakes domains like healthcare and finance.',hint:'Transparency in AI decision-making.' },
  { id:'e3',category:'ethics',difficulty:'medium',question:'What is AI alignment?',options:['Aligning text in AI-generated documents','Making AI systems pursue goals and values beneficial to humans','Aligning multiple AI systems to work together','Making AI models consistent in outputs'],answer:1,explanation:'AI alignment research works to ensure AI systems reliably do what humans intend.',hint:'Getting AI to want what we want.' },
  { id:'e4',category:'ethics',difficulty:'easy',question:'What is a deepfake?',options:['A very deep neural network','A fake dataset for model training','AI-generated synthetic media that realistically replaces real people faces or voices','A deep web security threat'],answer:2,explanation:'Deepfakes use GANs to create convincing fake videos/audio of real people.',hint:'Realistic AI-generated impersonation.' },
  { id:'e5',category:'ethics',difficulty:'medium',question:'What does AGI stand for?',options:['Applied General Intelligence','Artificial General Intelligence – AI with human-level ability across all cognitive tasks','Automated Governance Infrastructure','Advanced GPU Integration'],answer:1,explanation:'AGI refers to AI systems that can perform any intellectual task that a human can.',hint:'The holy grail of AI research.' },
  { id:'e6',category:'ethics',difficulty:'medium',question:'What is data poisoning?',options:['Deleting training data','Corrupting or manipulating training data to influence AI model behavior maliciously','Adding noise to data for privacy','A method to clean dirty datasets'],answer:1,explanation:'Data poisoning injects malicious examples into training data, causing the model to learn harmful patterns.',hint:'Attacking AI through its training data.' },
  { id:'e7',category:'ethics',difficulty:'hard',question:'What is the EU AI Act primary purpose?',options:['To promote AI development in Europe','To create a risk-based regulatory framework for AI systems used in the EU','To standardize AI programming languages','To fund AI research across European universities'],answer:1,explanation:'The EU AI Act categorizes AI systems by risk level and imposes corresponding requirements.',hint:'Europe landmark AI regulation.' },
  { id:'e8',category:'ethics',difficulty:'easy',question:'What is the Turing Test?',options:['A speed benchmark for AI models','A test where a machine must convince a human judge it is also human through conversation','A test for measuring machine learning accuracy','A security protocol for AI systems'],answer:1,explanation:'The Turing Test evaluates whether a machine natural language conversation is indistinguishable from a human.',hint:'Can a machine pass as human in conversation?' },
  { id:'e9',category:'ethics',difficulty:'medium',question:'What is algorithmic fairness?',options:['Ensuring all algorithms run at equal speed','Ensuring AI/ML decisions do not systematically disadvantage protected groups','Fair distribution of computing resources','Open-source access to AI algorithms'],answer:1,explanation:'Algorithmic fairness involves measuring and mitigating disparate impact across demographic groups.',hint:'Equal treatment across all groups.' },
  { id:'e10',category:'ethics',difficulty:'easy',question:'What is responsible AI?',options:['AI that takes responsibility for its mistakes','Developing and deploying AI with ethical considerations: fairness, safety, transparency, and accountability','AI that responds to user requests reliably','AI systems with reliable uptime guarantees'],answer:1,explanation:'Responsible AI encompasses practices to ensure AI systems are trustworthy, fair, and aligned with human values.',hint:'Ethics throughout the AI lifecycle.' },
];

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const category = searchParams.get('category');
  const count = parseInt(searchParams.get('count') || '10');

  let pool = category ? QUIZ_QUESTIONS.filter((q) => q.category === category) : QUIZ_QUESTIONS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5).slice(0, count);

  return NextResponse.json({ questions: shuffled, total: pool.length });
}
